name = "wind-app-for-greg"
main = "./src/index.ts"
compatibility_date = "2026-04-24"

[observability]
enabled = true

[vars]
EMAIL_FROM = "weather@rmcd.cc"
NWS_USER_AGENT = "(WindAppForGreg, weather.rmcd.cc)"

[[send_email]]
name = "EMAIL"
allowed_sender_addresses = ["weather@rmcd.cc"]

[[d1_databases]]
binding = "DB"
database_name = "wind-app-for-greg"
database_id = "3d807f73-0109-47e2-9bb1-af3acd59db82"

[assets]
directory = "../web/dist"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"

[[routes]]
pattern = "weather.rmcd.cc/*"
zone_name = "rmcd.cc"
